---
title: "PHP2517 Final Project"
author: "Peirong Hao, William Qian"
output:
  pdf_document: default
header-includes: \usepackage{fvextra} \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---

```{r setup, include=FALSE}
# https://yihui.org/knitr/options/
knitr::opts_chunk$set(message=FALSE, 
                      warning=FALSE, 
                      error=FALSE, 
                      echo = FALSE, 
                      fig.pos = "H" ,
                      fig.align = 'center',
                      tidy=TRUE, tidy.opts=list(width.cutoff=80))

library(tidyverse)
library(knitr)
set.seed(123)
library(tidyr)       ## Used to tidy data
library(dplyr)       ## Used to manipulate data
library(gtsummary)
```

```{r}
library(readxl)
df.chronic <-read_excel('hosp_eolchronic_dead6699ffs_2019.xlsx')

#first convert columns to factor or numeric columns

#relevel: first level is state, second level is region
#https://www.bu.edu/brand/guidelines/editorial-style/us-state-abbreviations/
#https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf
#Note: 1 state is US(unsure), so remove that obervation

df.chronic <- df.chronic %>% mutate_if(is.character,as.factor) %>% 
  mutate(across(.cols = c(
  `SNF/Long-Term Care Sector Reimbursements per Decedent during the Last Two Years of Life`,
  `Hospice Sector Reimbursements per Decedent during the Last Two Years of Life`,
  `Total ICU Bed Inputs per 1,000 Decedents during the Last Two Years of Life`,
  `High-Intensity ICU Bed Inputs per 1,000 Decedents during the Last Two Years of Life`,
  `Intermediate-Intensity ICU Bed Inputs per 1,000 Decedents during the Last Two Years of Life`,
  `Medical & Surgical Unit Bed Inputs per 1,000 Decedents during the Last Two Years of Life`,
  `SNF Bed Inputs per 1,000 Dededents during the Last Two Years of Life`,,
  `RNs Required Under Proposed Federal Standards per 1,000 Decedents during the Last Two Years of Life`,
  `High-Intensity ICU Days per Decedent during the Last Six Months of Life`,
  `Intermediate-Intensity ICU Days per Decedent during the Last Six Months of Life`,
  `Medical & Surgical Unit Days per Decedent during the Last Six Months of Life`,
  `Percent of Decedents Enrolled In Hospice during the Last Six Months of Life`,
  `Hospice Days per Decedent during the Last Six Months of Life`),~as.numeric(.)))%>%
  mutate(Region = case_when(State %in% c("CT","ME","MA","NH","RI","VT","NJ","NY","PA") ~ "Northeast",
                            State %in% c("IN","IL","MI","OH","WI","IA","KS","MN","MO","NE","ND","SD") ~ "Midwest",
                            State %in% c("DE","DC","FL","GA","MD","NC","SC","VA","WV","AL","KY","MS","TN","AR","LA","OK","TX") ~ "South",
                            State %in% c("AZ","CO","ID","NM","MT","UT","NV","WY","AK","CA","HI","OR","WA") ~ "West"),
         Region = factor(Region))%>% 
  filter(!is.na(Region))

# summary(df.chronic)
# summary(df.chronic$State)
# summary(df.chronic$Region)

#proposal: association between variables and outcome, clear y, x 
#model selection: aic, model assumption 


# Level 1: State
# Level 2: Region
```

```{r}
library(dplyr)
library(kableExtra)

overall_summary <- df.chronic %>%
  group_by(Region, State) %>% 
  summarise(
  n = (length(`Number of deaths among chronically ill patients assigned to hospital`)-sum(is.na(`Number of deaths among chronically ill patients assigned to hospital`))),
  total = sum(`Number of deaths among chronically ill patients assigned to hospital`, na.rm = T),
  mean = round(mean(`Number of deaths among chronically ill patients assigned to hospital`, na.rm = T), 3),
  sd = round(sd(`Number of deaths among chronically ill patients assigned to hospital`, na.rm = T), 3),
  median = round(median(`Number of deaths among chronically ill patients assigned to hospital`, na.rm = T), 3),
  min = round(min(`Number of deaths among chronically ill patients assigned to hospital`, na.rm = T), 3),
  max = round(max(`Number of deaths among chronically ill patients assigned to hospital`, na.rm = T), 3))%>%
  ungroup()

#output table for overall averages
overall_summary %>%
  mutate_all(linebreak) %>%
  kbl(caption = "Summary of Number of deaths",
  col.names=linebreak(c("Region", "State", "N", "Total", "Mean", "SD", "Median", "Min", "Max")),
  booktabs=T, escape=F, align = "c") %>%
kable_styling(full_width = FALSE, latex_options = c('hold_position'))
```

```{r}
df.chronic %>%
  group_by(State) %>%
  summarise(var_dead = var(`Number of deaths among chronically ill patients assigned to hospital`)) %>%
  ggplot(aes(x = State, y = var_dead)) +
  geom_bar(stat = "identity") +
  labs(title = "Variance of Number of deaths by States",
       x = "States",
       y = "Variance of Number of deaths") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
df.chronic %>%
  group_by(Region) %>%
  summarise(var_dead = var(`Number of deaths among chronically ill patients assigned to hospital`)) %>%
  ggplot(aes(x = Region, y = var_dead)) +
  geom_bar(stat = "identity") +
  labs(title = "Variance of Number of deaths by Region",
       x = "States",
       y = "Variance of Number of Region") +
  theme_minimal()
```

```{r}
cols_to_drop <- c("HRR", "HRR Name", "Provider ID", "Hospital Name", "City", "System", "Inpatient Sector Reimbursements per Decedent during the Last Two Years of Life", "Outpatient Sector Reimbursements per Decedent during the Last Two Years of Life", "SNF/Long-Term Care Sector Reimbursements per Decedent during the Last Two Years of Life", "Home Health Sector Reimbursements per Decedent during the Last Two Years of Life", "Hospice Sector Reimbursements per Decedent during the Last Two Years of Life", "Reimbursements for Durable Medical Equipment per Decedent during the Last Two Years of Life", "Ambulance spending per Decedent during the last two years of life", "Part B Spending for Evaluation & Management per Decedent during the Last Two Years of Life","Part B Spending for Procedures per Decedent during the Last Two Years of Life", "Part B Spending for Imaging per Decedent during the Last Two Years of Life", "Part B Spending for Tests per Decedent during the Last Two Years of Life", "Other Part B spending per Decedent during the last two years of life", "Inpatient Days per Decedent during the Last Two Years of Life", "Reimbursements per patient day (calculated)", "Reimbursements per Day: Ratio to US Average (calculated)", "Hospital reimbursements per Decedent during the last two years of life", "Payments per physician visit (calculated)", "Payments for physician visits per Decedent during the last two years of life", "Physician Visits per Decedent during the Last Two Years of Life", "Payments per visit: Ratio to US Average (calculated)", "FTE Physician Labor Inputs per 1,000 Decedents during the Last Two Years of Life", "FTE Medical Specialist Labor Inputs per 1,000 Decedents during the Last Two Years of Life", "FTE Primary Care Physician Labor Inputs per 1,000 Decedents during the Last Two Years of Life", "Average Co-Payments for Physician Services per Decedent during the Last Two Years of Life", "Average Co-Payments for Durable Medical Equipment per Decedent during the Last Two Years of Life", "Percent of Deaths Occurring In Hospital", "Percent of Deaths Associated With ICU Admission", "Physician Visits per Decedent during the Last Six Months of Life", "Medical Specialist Visits per Decedent during the Last Six Months of Life", "Primary Care Visits per Decedent during the Last Six Months of Life", "Percent of Decedents Seeing 10 or More Different Physicians during the Last Six Months of Life")

df.chronic <- df.chronic %>% select(-cols_to_drop)
```


```{r}
df.chronic[df.chronic<0] <- NA
# add check for proportion of zeros in each column!!!
df.chronic <- df.chronic %>% drop_na()
```

```{r}
df.chronic %>%
  select(-State) %>%
  group_by(Region) %>%
  summarize_all(~mean(., na.rm = TRUE))
```

```{r}
df.summary<-df.chronic %>% select(-c(State)) %>%
  tbl_summary(missing="no",
              by = Region, 
              type = list(where(is.numeric) ~ "continuous"),
              statistic = list(all_continuous() ~ "{mean} ({sd})")) %>% add_p()%>%
  modify_caption("Summary of Variables by Region")
df.summary
```

```{r}
df.numeric <- df.chronic %>%  select_if(is.numeric)
cor.df.numeric <- cor(df.numeric, use = "complete.obs")
# library(corrplot)
# corrplot(cor(cor.df.numeric),
#   method = "number",
#   type = "upper" # show only upper side
# )
#corrplot(cor.core_temp_numeric, title="Correlation Plot", mar=c(0,0,2,0), cex.main=0.7, number.cex=0.7, tl.cex = 0.7, cl.cex = 0.7)


#https://stackoverflow.com/questions/20030646/reformat-a-correlation-matrix-in-r-to-remove-row-names-column-names-and-cells
dat <- as.matrix(cor.df.numeric)
dimnames(dat) <- list(rep("", ncol(dat)), rep("", ncol(dat)))
dat[upper.tri(dat)] <- NA
print(dat, na.print = " ") 

library(corrplot)
#corrplot(dat, method = "number", type = "lower" , title="Correlation Plot", mar=c(0,0,1,0), cex.main=0.7, number.cex=0.7, tl.cex = 0.7, cl.cex = 0.7)
corrplot(dat, type = "lower" , title="Correlation Plot", mar=c(0,0,0,0), cex.main=0.7, number.cex=0.7, tl.cex = 0.7, cl.cex = 0.7)
#corrplot(cor.core_temp_numeric, title="Correlation Plot", mar=c(0,0,2,0), cex.main=0.7, number.cex=0.7, tl.cex = 0.7, cl.cex = 0.7)

#https://r-graph-gallery.com/74-margin-and-oma-cheatsheet.html
```




